name: CI

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  ci:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    services:
      redis:
        image: redis
        ports:
          # Maps port 6379 on service container to the host
          - 6379:6379

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          cache: true

      - name: Check formatting, linting and run tests
        run: deno task ok

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: iuioiua-redis-coverage
          entrypoint: jsr:@std/http/file-server
          root: coverage/html
